application: hyweb-mobilegip-apps
version: 5
runtime: php55
api_version: 1
threadsafe: yes
instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 3  # default value
  min_pending_latency: 500ms  # default value
  max_pending_latency: 15s


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$



handlers:
- url: /module_test
  script: manydevices/module_test.php
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /registerDevice
  script: registerDevice.php

- url: /my_adodb_test
  script: my_adodb_test.php

- url: /notificationConsole
  script: notificationConsole.php
  

- url: /images
  static_dir: images

- url: /admin
  script: admin.php

- url: /import
  script: import.php

- url: /login_test
  script: login_test.php

- url: /sale_statistics
  script: sale_statistics.php

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /cert
  static_dir: cert
  application_readable: true

- url: /(.+\.php)
  script: /\1
  
- url: /health_consultant/(.+\.php)
  script: /health_consultant/\1
  
- url: /(.+\.html)
  script: /\1
  

- url: .*
  script: main.php

